import type { Env } from "../types";

export const PERMISSIONS = [
  { id: "perm_dashboard_view", key: "dashboard.view", module: "dashboard", description: "View dashboard overview", critical: false },
  { id: "perm_users_view", key: "users.view", module: "users", description: "View users and access records", critical: true },
  { id: "perm_users_create", key: "users.create", module: "users", description: "Create user accounts", critical: true },
  { id: "perm_users_update", key: "users.update", module: "users", description: "Update user accounts", critical: true },
  { id: "perm_users_disable", key: "users.disable", module: "users", description: "Disable or lock user accounts", critical: true },
  { id: "perm_roles_view", key: "roles.view", module: "roles", description: "View roles", critical: true },
  { id: "perm_roles_create", key: "roles.create", module: "roles", description: "Create roles", critical: true },
  { id: "perm_roles_update", key: "roles.update", module: "roles", description: "Update roles", critical: true },
  { id: "perm_roles_assign_permissions", key: "roles.assign_permissions", module: "roles", description: "Assign permissions to roles", critical: true },
  { id: "perm_role_mappings_view", key: "role_mappings.view", module: "role_mappings", description: "View role mapping rules and previews", critical: true },
  { id: "perm_role_mappings_manage", key: "role_mappings.manage", module: "role_mappings", description: "Create and manage role mapping rules", critical: true },
  { id: "perm_role_mappings_apply", key: "role_mappings.apply", module: "role_mappings", description: "Apply role mappings to employee-linked users", critical: true },
  { id: "perm_access_scopes_view", key: "access_scopes.view", module: "access_scopes", description: "View role and user data access scopes", critical: true },
  { id: "perm_access_scopes_manage", key: "access_scopes.manage", module: "access_scopes", description: "Create and manage role and user data access scopes", critical: true },
  { id: "perm_access_scopes_apply", key: "access_scopes.apply", module: "access_scopes", description: "Apply data access scopes to users or access templates", critical: true },
  { id: "perm_settings_view", key: "settings.view", module: "settings", description: "View system settings", critical: true },
  { id: "perm_settings_manage", key: "settings.manage", module: "settings", description: "Manage system settings", critical: true },
  { id: "perm_organization_view", key: "organization.view", module: "organization", description: "View organization master data", critical: false },
  { id: "perm_organization_manage", key: "organization.manage", module: "organization", description: "Manage organization master data", critical: false },
  { id: "perm_employees_view", key: "employees.view", module: "employees", description: "View employee records", critical: false },
  { id: "perm_employees_create", key: "employees.create", module: "employees", description: "Create employee records", critical: false },
  { id: "perm_employees_update", key: "employees.update", module: "employees", description: "Update employee records", critical: false },
  { id: "perm_employees_archive", key: "employees.archive", module: "employees", description: "Archive employee records", critical: false },
  { id: "perm_employees_status_manage", key: "employees.status.manage", module: "employees", description: "Manage employee statuses and status changes", critical: false },
  { id: "perm_employees_numbering_manage", key: "employees.numbering.manage", module: "employees", description: "Manage employee numbering settings", critical: false },
  { id: "perm_employees_sensitive_view", key: "employees.sensitive.view", module: "employees", description: "View sensitive employee fields", critical: false },
  { id: "perm_employees_sensitive_update", key: "employees.sensitive.update", module: "employees", description: "Update sensitive employee fields", critical: false },
  { id: "perm_employees_job_history_view", key: "employees.job_history.view", module: "employees", description: "View employee job history", critical: false },
  { id: "perm_employees_job_history_manage", key: "employees.job_history.manage", module: "employees", description: "Manage employee job history", critical: false },
  { id: "perm_employees_contacts_view", key: "employees.contacts.view", module: "employees", description: "View employee contacts", critical: false },
  { id: "perm_employees_contacts_manage", key: "employees.contacts.manage", module: "employees", description: "Manage employee contacts", critical: false },
  { id: "perm_employees_onboarding_manage", key: "employees.onboarding.manage", module: "employees", description: "Manage employee onboarding tasks", critical: false },
  { id: "perm_attendance_view", key: "attendance.view", module: "attendance", description: "View attendance records", critical: false },
  { id: "perm_attendance_manage", key: "attendance.manage", module: "attendance", description: "Manage attendance records", critical: false },
  { id: "perm_attendance_correct", key: "attendance.correct", module: "attendance", description: "Request attendance corrections", critical: false },
  { id: "perm_attendance_approve_correction", key: "attendance.approve_correction", module: "attendance", description: "Approve or reject attendance corrections", critical: false },
  { id: "perm_attendance_devices_manage", key: "attendance.devices.manage", module: "attendance", description: "Manage attendance devices and raw imports", critical: false },
  { id: "perm_attendance_settings_manage", key: "attendance.settings.manage", module: "attendance", description: "Manage attendance settings", critical: false },
  { id: "perm_attendance_reports_view", key: "attendance.reports.view", module: "attendance", description: "View attendance reports", critical: false },
  { id: "perm_attendance_reports_export", key: "attendance.reports.export", module: "attendance", description: "Export attendance reports", critical: false },
  { id: "perm_attendance_logs_view", key: "attendance.logs.view", module: "attendance", description: "View attendance logs", critical: false },
  { id: "perm_attendance_logs_manage", key: "attendance.logs.manage", module: "attendance", description: "Manage attendance logs", critical: false },
  { id: "perm_attendance_manual_entries_manage", key: "attendance.manual_entries.manage", module: "attendance", description: "Create manual attendance entries", critical: false },
  { id: "perm_attendance_daily_refresh", key: "attendance.daily.refresh", module: "attendance", description: "Refresh daily attendance records", critical: false },
  { id: "perm_attendance_payroll_impact_view", key: "attendance.payroll_impact.view", module: "attendance", description: "View attendance payroll impact", critical: false },
  { id: "perm_attendance_corrections_view", key: "attendance.corrections.view", module: "attendance", description: "View attendance correction requests", critical: false },
  { id: "perm_attendance_corrections_create", key: "attendance.corrections.create", module: "attendance", description: "Create attendance correction requests", critical: false },
  { id: "perm_attendance_corrections_review", key: "attendance.corrections.review", module: "attendance", description: "Review attendance correction requests", critical: false },
  { id: "perm_attendance_corrections_approve", key: "attendance.corrections.approve", module: "attendance", description: "Approve attendance correction requests", critical: false },
  { id: "perm_attendance_corrections_reject", key: "attendance.corrections.reject", module: "attendance", description: "Reject attendance correction requests", critical: false },
  { id: "perm_attendance_corrections_cancel", key: "attendance.corrections.cancel", module: "attendance", description: "Cancel attendance correction requests", critical: false },
  { id: "perm_attendance_corrections_manage", key: "attendance.corrections.manage", module: "attendance", description: "Manage attendance correction requests", critical: false },
  { id: "perm_attendance_lock_override", key: "attendance.lock.override", module: "attendance", description: "Override payroll-locked attendance records", critical: false },
  { id: "perm_attendance_day_overrides_view", key: "attendance.day_overrides.view", module: "attendance", description: "View attendance day overrides", critical: false },
  { id: "perm_attendance_day_overrides_manage", key: "attendance.day_overrides.manage", module: "attendance", description: "Manage attendance day overrides", critical: false },
  { id: "perm_payroll_attendance_impacts_view", key: "payroll.attendance_impacts.view", module: "payroll", description: "View payroll attendance impacts", critical: false },
  { id: "perm_payroll_attendance_impacts_manage", key: "payroll.attendance_impacts.manage", module: "payroll", description: "Manage payroll attendance impacts", critical: false },
  { id: "perm_payroll_leave_deductions_view", key: "payroll.leave_deductions.view", module: "payroll", description: "View leave deduction payroll impacts", critical: false },
  { id: "perm_payroll_leave_deductions_manage", key: "payroll.leave_deductions.manage", module: "payroll", description: "Manage leave deduction payroll impacts", critical: false },
  { id: "perm_employees_attendance_view", key: "employees.attendance.view", module: "employees", description: "View Employee 360 attendance information", critical: false },
  { id: "perm_leave_view", key: "leave.view", module: "leave", description: "View leave records", critical: false },
  { id: "perm_leave_manage", key: "leave.manage", module: "leave", description: "Manage leave records", critical: false },
  { id: "perm_leave_request", key: "leave.request", module: "leave", description: "Create leave requests", critical: false },
  { id: "perm_leave_approve", key: "leave.approve", module: "leave", description: "Approve or reject assigned leave requests", critical: false },
  { id: "perm_leave_cancel", key: "leave.cancel", module: "leave", description: "Cancel leave requests", critical: false },
  { id: "perm_leave_settings_manage", key: "leave.settings.manage", module: "leave", description: "Manage leave types and policies", critical: false },
  { id: "perm_leave_workflow_manage", key: "leave.workflow.manage", module: "leave", description: "Manage leave approval workflows", critical: false },
  { id: "perm_leave_requests_create", key: "leave.requests.create", module: "leave", description: "Create leave requests with granular leave permission", critical: false },
  { id: "perm_leave_requests_approve", key: "leave.requests.approve", module: "leave", description: "Approve leave requests with granular leave permission", critical: false },
  { id: "perm_leave_requests_reject", key: "leave.requests.reject", module: "leave", description: "Reject leave requests with granular leave permission", critical: false },
  { id: "perm_leave_requests_cancel", key: "leave.requests.cancel", module: "leave", description: "Cancel leave requests with granular leave permission", critical: false },
  { id: "perm_leave_requests_manage", key: "leave.requests.manage", module: "leave", description: "Manage leave requests with granular leave permission", critical: false },
  { id: "perm_leave_types_manage", key: "leave.types.manage", module: "leave", description: "Manage leave types with granular leave permission", critical: false },
  { id: "perm_leave_policies_manage", key: "leave.policies.manage", module: "leave", description: "Manage leave policies with granular leave permission", critical: false },
  { id: "perm_leave_approval_workflows_view", key: "leave.approval_workflows.view", module: "leave", description: "View leave approval workflows", critical: false },
  { id: "perm_leave_approval_workflows_manage", key: "leave.approval_workflows.manage", module: "leave", description: "Manage leave approval workflows", critical: false },
  { id: "perm_leave_balances_adjust", key: "leave.balances.adjust", module: "leave", description: "Adjust leave balance cycles and ledger", critical: false },
  { id: "perm_leave_payroll_impact_view", key: "leave.payroll_impact.view", module: "leave", description: "View leave payroll impact estimates", critical: false },
  { id: "perm_leave_payroll_impact_manage", key: "leave.payroll_impact.manage", module: "leave", description: "Manage leave payroll impact records", critical: false },
  { id: "perm_leave_requests_waive_document", key: "leave.requests.waive_document", module: "leave", description: "Waive leave supporting document requirements", critical: false },
  { id: "perm_leave_reports_view", key: "leave.reports.view", module: "leave", description: "View leave reports", critical: false },
  { id: "perm_leave_reports_export", key: "leave.reports.export", module: "leave", description: "Export leave reports", critical: false },
  { id: "perm_employees_leave_view", key: "employees.leave.view", module: "employees", description: "View Employee 360 leave information", critical: false },
  { id: "perm_payroll_view", key: "payroll.view", module: "payroll", description: "View payroll records", critical: false },
  { id: "perm_payroll_manage", key: "payroll.manage", module: "payroll", description: "Manage payroll records", critical: false },
  { id: "perm_payroll_settings_manage", key: "payroll.settings.manage", module: "payroll", description: "Manage payroll settings", critical: false },
  { id: "perm_payroll_approve", key: "payroll.approve", module: "payroll", description: "Approve payroll runs and adjustments", critical: false },
  { id: "perm_payroll_pay", key: "payroll.pay", module: "payroll", description: "Mark payroll runs and advances as paid", critical: false },
  { id: "perm_payroll_reports_view", key: "payroll.reports.view", module: "payroll", description: "View payroll reports", critical: false },
  { id: "perm_payroll_reports_export", key: "payroll.reports.export", module: "payroll", description: "Export payroll reports", critical: false },
  { id: "perm_payroll_reports_sensitive_view", key: "payroll.reports.sensitive.view", module: "payroll", description: "View sensitive payroll report values", critical: false },
  { id: "perm_payroll_advances_view", key: "payroll.advances.view", module: "payroll", description: "View payroll advance payments", critical: false },
  { id: "perm_payroll_advances_manage", key: "payroll.advances.manage", module: "payroll", description: "Manage payroll advance payments", critical: false },
  { id: "perm_payroll_advances_approve", key: "payroll.advances.approve", module: "payroll", description: "Approve payroll advances in Payroll Core", critical: false },
  { id: "perm_payroll_advances_cancel", key: "payroll.advances.cancel", module: "payroll", description: "Cancel payroll advances in Payroll Core", critical: false },
  { id: "perm_payroll_adjustments_manage", key: "payroll.adjustments.manage", module: "payroll", description: "Manage payroll adjustments", critical: false },
  { id: "perm_payroll_adjustments_view", key: "payroll.adjustments.view", module: "payroll", description: "View payroll adjustments", critical: false },
  { id: "perm_payroll_adjustments_approve_placeholder", key: "payroll.adjustments.approve_placeholder", module: "payroll", description: "Approve payroll adjustments as Payroll Core placeholders", critical: false },
  { id: "perm_payroll_components_manage", key: "payroll.components.manage", module: "payroll", description: "Manage payroll components", critical: false },
  { id: "perm_payroll_components_view", key: "payroll.components.view", module: "payroll", description: "View payroll components", critical: false },
  { id: "perm_payroll_deductions_view", key: "payroll.deductions.view", module: "payroll", description: "View payroll deductions", critical: false },
  { id: "perm_payroll_deductions_manage", key: "payroll.deductions.manage", module: "payroll", description: "Manage payroll deductions", critical: false },
  { id: "perm_payroll_periods_view", key: "payroll.periods.view", module: "payroll", description: "View payroll periods", critical: false },
  { id: "perm_payroll_periods_create", key: "payroll.periods.create", module: "payroll", description: "Create payroll periods", critical: false },
  { id: "perm_payroll_periods_update", key: "payroll.periods.update", module: "payroll", description: "Update payroll periods", critical: false },
  { id: "perm_payroll_periods_manage", key: "payroll.periods.manage", module: "payroll", description: "Manage payroll periods", critical: false },
  { id: "perm_payroll_periods_calculate", key: "payroll.periods.calculate", module: "payroll", description: "Calculate payroll periods", critical: false },
  { id: "perm_payroll_periods_recalculate", key: "payroll.periods.recalculate", module: "payroll", description: "Recalculate payroll periods", critical: false },
  { id: "perm_payroll_periods_cancel", key: "payroll.periods.cancel", module: "payroll", description: "Cancel payroll periods", critical: false },
  { id: "perm_payroll_periods_lock", key: "payroll.periods.lock", module: "payroll", description: "Lock payroll periods", critical: false },
  { id: "perm_payroll_periods_unlock", key: "payroll.periods.unlock", module: "payroll", description: "Unlock payroll periods", critical: false },
  { id: "perm_payroll_periods_approve_placeholder", key: "payroll.periods.approve_placeholder", module: "payroll", description: "Approve payroll periods as placeholders", critical: false },
  { id: "perm_payroll_periods_finalize_placeholder", key: "payroll.periods.finalize_placeholder", module: "payroll", description: "Finalize payroll periods as placeholders", critical: false },
  { id: "perm_payroll_runs_view", key: "payroll.runs.view", module: "payroll", description: "View payroll runs", critical: false },
  { id: "perm_payroll_runs_manage", key: "payroll.runs.manage", module: "payroll", description: "Manage payroll runs", critical: false },
  { id: "perm_payroll_runs_calculate", key: "payroll.runs.calculate", module: "payroll", description: "Calculate payroll runs", critical: false },
  { id: "perm_payroll_runs_recalculate", key: "payroll.runs.recalculate", module: "payroll", description: "Recalculate payroll runs", critical: false },
  { id: "perm_payroll_runs_cancel", key: "payroll.runs.cancel", module: "payroll", description: "Cancel payroll runs", critical: false },
  { id: "perm_payroll_runs_approve_placeholder", key: "payroll.runs.approve_placeholder", module: "payroll", description: "Approve payroll runs as placeholders", critical: false },
  { id: "perm_payroll_runs_finalize_placeholder", key: "payroll.runs.finalize_placeholder", module: "payroll", description: "Finalize payroll runs as placeholders", critical: false },
  { id: "perm_payroll_results_view", key: "payroll.results.view", module: "payroll", description: "View payroll results", critical: false },
  { id: "perm_payroll_results_detail_view", key: "payroll.results.detail.view", module: "payroll", description: "View payroll result line details", critical: false },
  { id: "perm_payroll_results_sensitive_view", key: "payroll.results.sensitive.view", module: "payroll", description: "View sensitive payroll result values", critical: false },
  { id: "perm_payroll_results_update", key: "payroll.results.update", module: "payroll", description: "Update payroll result rows", critical: false },
  { id: "perm_payroll_approve_placeholder", key: "payroll.approve_placeholder", module: "payroll", description: "Approve payroll placeholders", critical: false },
  { id: "perm_payroll_finalize_placeholder", key: "payroll.finalize_placeholder", module: "payroll", description: "Finalize payroll placeholders", critical: false },
  { id: "perm_payroll_lock", key: "payroll.lock", module: "payroll", description: "Lock payroll core periods", critical: false },
  { id: "perm_payroll_unlock", key: "payroll.unlock", module: "payroll", description: "Unlock payroll core periods", critical: false },
  { id: "perm_payroll_cutoff_override", key: "payroll.cutoff.override", module: "payroll", description: "Override payroll cutoff rules with reason", critical: false },
  { id: "perm_payroll_approvals_view", key: "payroll.approvals.view", module: "payroll", description: "View payroll approval history", critical: false },
  { id: "perm_payroll_approvals_submit", key: "payroll.approvals.submit", module: "payroll", description: "Submit payroll runs for approval", critical: false },
  { id: "perm_payroll_approvals_approve", key: "payroll.approvals.approve", module: "payroll", description: "Approve submitted payroll runs", critical: false },
  { id: "perm_payroll_approvals_reject", key: "payroll.approvals.reject", module: "payroll", description: "Reject submitted payroll runs", critical: false },
  { id: "perm_payroll_approvals_send_back", key: "payroll.approvals.send_back", module: "payroll", description: "Send submitted payroll runs back for changes", critical: false },
  { id: "perm_payroll_approvals_manage", key: "payroll.approvals.manage", module: "payroll", description: "Manage payroll approvals", critical: false },
  { id: "perm_payroll_finalization_view", key: "payroll.finalization.view", module: "payroll", description: "View payroll finalization status", critical: false },
  { id: "perm_payroll_finalization_finalize", key: "payroll.finalization.finalize", module: "payroll", description: "Finalize approved payroll runs", critical: false },
  { id: "perm_payroll_finalization_unlock", key: "payroll.finalization.unlock", module: "payroll", description: "Unlock finalized payroll runs with reason", critical: false },
  { id: "perm_payroll_finalization_manage", key: "payroll.finalization.manage", module: "payroll", description: "Manage payroll finalization", critical: false },
  { id: "perm_payroll_override_finalized", key: "payroll.override_finalized", module: "payroll", description: "Override finalized payroll restrictions", critical: true },
  { id: "perm_payroll_unlock_after_finalization", key: "payroll.unlock_after_finalization", module: "payroll", description: "Unlock payroll after finalization", critical: true },
  { id: "perm_payroll_payslips_view", key: "payroll.payslips.view", module: "payroll", description: "View payroll payslips", critical: false },
  { id: "perm_payroll_payslips_generate", key: "payroll.payslips.generate", module: "payroll", description: "Generate payroll payslips", critical: false },
  { id: "perm_payroll_payslips_regenerate", key: "payroll.payslips.regenerate", module: "payroll", description: "Regenerate payroll payslips", critical: false },
  { id: "perm_payroll_payslips_download", key: "payroll.payslips.download", module: "payroll", description: "Download payroll payslips", critical: false },
  { id: "perm_payroll_payslips_cancel", key: "payroll.payslips.cancel", module: "payroll", description: "Cancel payroll payslips", critical: false },
  { id: "perm_payroll_payslips_manage", key: "payroll.payslips.manage", module: "payroll", description: "Manage payroll payslips", critical: false },
  { id: "perm_payroll_payment_register_view", key: "payroll.payment_register.view", module: "payroll", description: "View payroll payment register", critical: false },
  { id: "perm_payroll_payment_register_prepare", key: "payroll.payment_register.prepare", module: "payroll", description: "Prepare payroll payment register", critical: false },
  { id: "perm_payroll_payment_register_confirm_manual_paid", key: "payroll.payment_register.confirm_manual_paid", module: "payroll", description: "Confirm payroll payments manually", critical: false },
  { id: "perm_payroll_payment_register_cancel", key: "payroll.payment_register.cancel", module: "payroll", description: "Cancel payroll payment register entries", critical: false },
  { id: "perm_payroll_payment_register_manage", key: "payroll.payment_register.manage", module: "payroll", description: "Manage payroll payment register", critical: false },
  { id: "perm_payroll_payment_register_sensitive_view", key: "payroll.payment_register.sensitive.view", module: "payroll", description: "View sensitive payment register fields", critical: false },
  { id: "perm_payroll_history_view", key: "payroll.history.view", module: "payroll", description: "View finalized payroll history", critical: false },
  { id: "perm_payroll_history_employee_view", key: "payroll.history.employee.view", module: "payroll", description: "View employee payroll history", critical: false },
  { id: "perm_employees_payroll_view", key: "employees.payroll.view", module: "employees", description: "View Employee 360 payroll information", critical: false },
  { id: "perm_employees_payroll_update", key: "employees.payroll.update", module: "employees", description: "Update Employee 360 payroll profile", critical: false },
  { id: "perm_roster_view", key: "roster.view", module: "roster", description: "View roster records", critical: false },
  { id: "perm_roster_manage", key: "roster.manage", module: "roster", description: "Manage roster records", critical: false },
  { id: "perm_roster_publish", key: "roster.publish", module: "roster", description: "Publish roster periods and manage published roster edits", critical: false },
  { id: "perm_roster_settings_view", key: "roster.settings.view", module: "roster", description: "View roster settings", critical: false },
  { id: "perm_roster_settings_update", key: "roster.settings.update", module: "roster", description: "Update roster settings", critical: false },
  { id: "perm_roster_settings_manage", key: "roster.settings.manage", module: "roster", description: "Manage roster settings and shift templates", critical: false },
  { id: "perm_roster_shift_templates_view", key: "roster.shift_templates.view", module: "roster", description: "View roster shift templates", critical: false },
  { id: "perm_roster_shift_templates_create", key: "roster.shift_templates.create", module: "roster", description: "Create roster shift templates", critical: false },
  { id: "perm_roster_shift_templates_update", key: "roster.shift_templates.update", module: "roster", description: "Update roster shift templates", critical: false },
  { id: "perm_roster_shift_templates_archive", key: "roster.shift_templates.archive", module: "roster", description: "Archive roster shift templates", critical: false },
  { id: "perm_roster_shift_templates_restore", key: "roster.shift_templates.restore", module: "roster", description: "Restore roster shift templates", critical: false },
  { id: "perm_roster_shift_templates_manage", key: "roster.shift_templates.manage", module: "roster", description: "Manage roster shift templates", critical: false },
  { id: "perm_roster_periods_view", key: "roster.periods.view", module: "roster", description: "View roster periods", critical: false },
  { id: "perm_roster_periods_create", key: "roster.periods.create", module: "roster", description: "Create roster periods", critical: false },
  { id: "perm_roster_periods_update", key: "roster.periods.update", module: "roster", description: "Update roster periods", critical: false },
  { id: "perm_roster_periods_publish", key: "roster.periods.publish", module: "roster", description: "Publish roster periods", critical: false },
  { id: "perm_roster_periods_unpublish", key: "roster.periods.unpublish", module: "roster", description: "Unpublish roster periods", critical: false },
  { id: "perm_roster_periods_lock", key: "roster.periods.lock", module: "roster", description: "Lock roster periods", critical: false },
  { id: "perm_roster_periods_unlock", key: "roster.periods.unlock", module: "roster", description: "Unlock roster periods", critical: false },
  { id: "perm_roster_periods_archive", key: "roster.periods.archive", module: "roster", description: "Archive roster periods", critical: false },
  { id: "perm_roster_periods_manage", key: "roster.periods.manage", module: "roster", description: "Manage roster periods", critical: false },
  { id: "perm_roster_assignments_view", key: "roster.assignments.view", module: "roster", description: "View roster assignments", critical: false },
  { id: "perm_roster_assignments_create", key: "roster.assignments.create", module: "roster", description: "Create roster assignments", critical: false },
  { id: "perm_roster_assignments_update", key: "roster.assignments.update", module: "roster", description: "Update roster assignments", critical: false },
  { id: "perm_roster_assignments_cancel", key: "roster.assignments.cancel", module: "roster", description: "Cancel roster assignments", critical: false },
  { id: "perm_roster_assignments_manage", key: "roster.assignments.manage", module: "roster", description: "Manage roster assignments", critical: false },
  { id: "perm_roster_assignments_bulk_update", key: "roster.assignments.bulk_update", module: "roster", description: "Bulk update roster assignments", critical: false },
  { id: "perm_roster_assignments_copy_week", key: "roster.assignments.copy_week", module: "roster", description: "Copy weekly roster assignments", critical: false },
  { id: "perm_roster_assignments_edit_after_publish", key: "roster.assignments.edit_after_publish", module: "roster", description: "Edit assignments after roster publish", critical: false },
  { id: "perm_roster_assignments_override_lock", key: "roster.assignments.override_lock", module: "roster", description: "Override locked roster assignments", critical: false },
  { id: "perm_roster_assignments_cross_worksite", key: "roster.assignments.cross_worksite", module: "roster", description: "Assign employees across worksites", critical: false },
  { id: "perm_roster_conflicts_view", key: "roster.conflicts.view", module: "roster", description: "View roster assignment conflicts", critical: false },
  { id: "perm_roster_conflicts_override", key: "roster.conflicts.override", module: "roster", description: "Override roster assignment conflicts", critical: false },
  { id: "perm_roster_team_view", key: "roster.team.view", module: "roster", description: "View team roster within access scope", critical: false },
  { id: "perm_roster_all_locations_view", key: "roster.all_locations.view", module: "roster", description: "View roster across allowed locations", critical: false },
  { id: "perm_roster_whole_company_view", key: "roster.whole_company.view", module: "roster", description: "View company-wide roster with matching scope", critical: false },
  { id: "perm_roster_reports_view", key: "roster.reports.view", module: "roster", description: "View roster reports", critical: false },
  { id: "perm_roster_reports_export", key: "roster.reports.export", module: "roster", description: "Export roster reports", critical: false },
  { id: "perm_employees_roster_view", key: "employees.roster.view", module: "employees", description: "View Employee 360 roster information", critical: false },
  { id: "perm_documents_view", key: "documents.view", module: "documents", description: "View documents", critical: false },
  { id: "perm_documents_upload", key: "documents.upload", module: "documents", description: "Upload documents", critical: false },
  { id: "perm_documents_download", key: "documents.download", module: "documents", description: "Download documents", critical: false },
  { id: "perm_documents_archive", key: "documents.archive", module: "documents", description: "Archive documents", critical: false },
  { id: "perm_documents_delete", key: "documents.delete", module: "documents", description: "Delete documents", critical: false },
  { id: "perm_documents_sensitive_view", key: "documents.sensitive.view", module: "documents", description: "View sensitive documents", critical: false },
  { id: "perm_documents_sensitive_download", key: "documents.sensitive.download", module: "documents", description: "Download sensitive documents", critical: false },
  { id: "perm_documents_settings_manage", key: "documents.settings.manage", module: "documents", description: "Manage document categories and types", critical: false },
  { id: "perm_documents_reports_view", key: "documents.reports.view", module: "documents", description: "View document reports", critical: false },
  { id: "perm_documents_reports_export", key: "documents.reports.export", module: "documents", description: "Export document reports", critical: false },
  { id: "perm_documents_registry_view", key: "documents.registry.view", module: "documents", description: "View central document registry", critical: false },
  { id: "perm_documents_required_rules_manage", key: "documents.required_rules.manage", module: "documents", description: "Manage required document rules", critical: false },
  { id: "perm_documents_permanent_delete", key: "documents.permanent_delete", module: "documents", description: "Permanently delete document records and files", critical: false },
  { id: "perm_assets_view", key: "assets.view", module: "assets", description: "View assets and uniforms", critical: false },
  { id: "perm_assets_manage", key: "assets.manage", module: "assets", description: "Manage assets and uniforms", critical: false },
  { id: "perm_assets_settings_manage", key: "assets.settings.manage", module: "assets", description: "Manage asset and uniform settings", critical: false },
  { id: "perm_assets_issue", key: "assets.issue", module: "assets", description: "Issue assets and uniforms", critical: false },
  { id: "perm_assets_return", key: "assets.return", module: "assets", description: "Return issued assets and uniforms", critical: false },
  { id: "perm_assets_damage", key: "assets.damage", module: "assets", description: "Mark assets and uniforms damaged", critical: false },
  { id: "perm_assets_lost", key: "assets.lost", module: "assets", description: "Mark assets and uniforms lost", critical: false },
  { id: "perm_assets_write_off", key: "assets.write_off", module: "assets", description: "Write off assets and uniforms", critical: false },
  { id: "perm_assets_deductions_manage", key: "assets.deductions.manage", module: "assets", description: "Manage asset recovery and deduction links", critical: false },
  { id: "perm_assets_reports_view", key: "assets.reports.view", module: "assets", description: "View asset reports", critical: false },
  { id: "perm_assets_reports_export", key: "assets.reports.export", module: "assets", description: "Export asset reports", critical: false },
  { id: "perm_employees_assets_view", key: "employees.assets.view", module: "employees", description: "View Employee 360 assets and uniforms", critical: false },
  { id: "perm_employee_notes_view", key: "employee_notes.view", module: "employee_notes", description: "View general employee notes", critical: false },
  { id: "perm_employee_notes_create", key: "employee_notes.create", module: "employee_notes", description: "Create employee notes", critical: false },
  { id: "perm_employee_notes_update", key: "employee_notes.update", module: "employee_notes", description: "Update employee notes", critical: false },
  { id: "perm_employee_notes_archive", key: "employee_notes.archive", module: "employee_notes", description: "Archive employee notes", critical: false },
  { id: "perm_employee_notes_restricted_view", key: "employee_notes.restricted.view", module: "employee_notes", description: "View restricted employee notes", critical: false },
  { id: "perm_employee_notes_restricted_manage", key: "employee_notes.restricted.manage", module: "employee_notes", description: "Create or edit restricted employee notes", critical: false },
  { id: "perm_employee_notes_attachments_manage", key: "employee_notes.attachments.manage", module: "employee_notes", description: "Manage employee note attachments", critical: false },
  { id: "perm_employees_audit_view", key: "employees.audit.view", module: "employees", description: "View Employee 360 audit timeline", critical: false },
  { id: "perm_reports_view", key: "reports.view", module: "reports", description: "View reports", critical: false },
  { id: "perm_reports_export", key: "reports.export", module: "reports", description: "Export reports from the report center", critical: false },
  { id: "perm_self_service_view", key: "self_service.view", module: "self_service", description: "Access employee self-service records linked to the current user", critical: false },
  { id: "perm_self_service_kyc_request", key: "self_service.kyc_request", module: "self_service", description: "Submit KYC/profile update requests for own employee profile", critical: false },
  { id: "perm_self_service_leave_request", key: "self_service.leave_request", module: "self_service", description: "Create leave requests from employee self-service", critical: false },
  { id: "perm_self_service_attendance_correction", key: "self_service.attendance_correction", module: "self_service", description: "Request attendance corrections from employee self-service", critical: false },
  { id: "perm_self_service_attendance_view", key: "self_service.attendance.view", module: "self_service", description: "View own attendance in employee self-service", critical: false },
  { id: "perm_self_service_attendance_correction_request", key: "self_service.attendance_correction.request", module: "self_service", description: "Request own attendance corrections from employee self-service", critical: false },
  { id: "perm_self_service_roster_view", key: "self_service.roster.view", module: "self_service", description: "View own published roster in employee self-service", critical: false },
  { id: "perm_self_service_payslips_view", key: "self_service.payslips.view", module: "self_service", description: "View own payslips in self-service", critical: false },
  { id: "perm_self_service_payslips_download", key: "self_service.payslips.download", module: "self_service", description: "Download own payslips in self-service", critical: false },
  { id: "perm_roster_self_view", key: "roster.self.view", module: "roster", description: "View own published roster", critical: false },
  { id: "perm_attendance_roster_context_view", key: "attendance.roster_context.view", module: "attendance", description: "Use roster schedule context in attendance views", critical: false },
  { id: "perm_leave_roster_context_view", key: "leave.roster_context.view", module: "leave", description: "Use roster work requirement context in leave calculation", critical: false },
  { id: "perm_audit_view", key: "audit.view", module: "audit", description: "View audit logs", critical: true },
  { id: "perm_audit_export", key: "audit.export", module: "audit", description: "Export audit logs", critical: false }
] as const;

export const OWNER_ROLE_NAME = "Owner/Super Admin";

export async function seedSystemPermissions(db: Env["DB"]) {
  const statements = PERMISSIONS.map((permission) =>
    db
      .prepare(
        `INSERT OR IGNORE INTO permissions (id, key, module, description, is_critical)
         VALUES (?, ?, ?, ?, ?)`
      )
      .bind(permission.id, permission.key, permission.module, permission.description, permission.critical ? 1 : 0)
  );
  await db.batch(statements);
}

export async function ensureOwnerRole(db: Env["DB"]) {
  const existing = await db.prepare("SELECT id FROM roles WHERE name = ?").bind(OWNER_ROLE_NAME).first<{ id: string }>();
  const roleId = existing?.id ?? crypto.randomUUID();

  if (!existing) {
    await db
      .prepare(
        `INSERT INTO roles (id, name, description, is_system_role, is_protected, is_active)
         VALUES (?, ?, ?, 1, 1, 1)`
      )
      .bind(roleId, OWNER_ROLE_NAME, "Protected system role with full HRM access.")
      .run();
  } else {
    await db
      .prepare("UPDATE roles SET is_system_role = 1, is_protected = 1, is_active = 1, updated_at = ? WHERE id = ?")
      .bind(new Date().toISOString(), roleId)
      .run();
  }

  await db
    .prepare(
      `INSERT OR IGNORE INTO role_permissions (role_id, permission_id)
       SELECT ?, id FROM permissions`
    )
    .bind(roleId)
    .run();

  return roleId;
}
